# Generated by Django 4.1.7 on 2023-04-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("years_of_experiences", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=1000)),
                ("name", models.CharField(max_length=50)),
                ("project", models.CharField(max_length=1000)),
                ("code", models.CharField(max_length=1000)),
                ("skils", models.ManyToManyField(to="website.skills")),
            ],
        ),
    ]
